### ISSUE TITLE
Erro em prestashop 1.6.0.9

### ISSUE THREAD

**Issue by netboy69** [chronopostpt/pickup-prestashop#2]
Boa tarde, estou a tentar instalar o modulo e nao me da, tenho o alojamento em cloud partilhado ja tenho a parta da firewall aberta e o ip do servidor, mesmo assim nao me funciona da me o erro: 

[PrestaShop] Fatal error in module pickme_chronopost:
Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://83.240.239.170:7790/ChronoWSB2CPointsv3/GetB2CPoints_v3Service?wsdl' : failed to load external entity "http://83.240.239.170:7790/ChronoWSB2CPointsv3/GetB2CPoints_v3Service?wsdl" in /home/wikopt/public_html/modules/pickme_chronopost/pickme_chronopost.php:74 Stack trace: #0 /home/wikopt/public_html/modules/pickme_chronopost/pickme_chronopost.php(74): SoapClient->SoapClient('http://83.240.2...', Array) #1 /home/wikopt/public_html/modules/pickme_chronopost/pickme_chronopost.php(120): pickme_chronopost->updateDatabase() #2 /home/wikopt/public_html/controllers/admin/AdminModulesController.php(805): pickme_chronopost->install() #3 /home/wikopt/public_html/controllers/admin/AdminModulesController.php(1045): AdminModulesControllerCore->postProcessCallback() #4 /home/wikopt/public_html/classes/controller/Controller.php(171): AdminModulesControllerCore->postProcess() #5 /home/wikopt/public_html/classes/Dispatcher.php(373): Contro

Alguem sabe o que podera ser?

Cumprimentos
Valter

**Comment by rjpsantos** [comment]
Olá,

Encontrou solução para o erro?

Pode partilhar?

Obrigado,

**Comment by brunomiguel88** [comment]
Olá,

Também obtenho o mesmo erro com a versão 1.6.22. Encontraram alguma solução que possam partilhar?

Obrigado
